const level = {
  id: "kordex7",
  order: 0,
  title: "Mundo 00 — KORDEX-7: A Primeira Sintonia",
  shortTitle: "KORDEX-7",
  status: "playable",
  playable: true,
  builderId: "floating-islands",
  totalFragments: 7,
  spawn: [0, 0.35, 14],
  initialCheckpointId: "entrada",
  killY: -26,
  theme: {
    atmosphere: "cosmic-fantasy",
    cordColor: 0x4de3ff,
    tunedColor: 0xff6ec7,
    crystalColor: 0xffd166,
  },
  islands: [
    { position: [0, 0, 14], radius: 5.5, checkpoint: { id: "entrada", label: "Entrada KORDEX-7" } },
    { position: [11, 1.5, 8], radius: 3.4 },
    { position: [16, 3, -2], radius: 3.2 },
    {
      position: [9, 4.5, -13],
      radius: 3,
      zorg: true,
      checkpoint: { id: "observatorio", label: "Observatório de Zorg" },
    },
    { position: [0, 6, -15], radius: 3.6, bob: 0.4 },
    { position: [-11.5, 7.5, -12], radius: 3 },
    {
      position: [-16, 9, -3],
      radius: 3.2,
      bob: 0.35,
      checkpoint: { id: "arco", label: "Arco das Cordas" },
    },
    { position: [-9, 10.5, 10], radius: 3 },
    {
      position: [0, 13.5, -2],
      radius: 4.6,
      portal: true,
      checkpoint: { id: "portal", label: "Portal de Retorno" },
    },
  ],
  cords: [
    { from: 0, to: 1 },
    { from: 1, to: 2 },
    { from: 2, to: 3, phantom: true },
    { from: 3, to: 4 },
    { from: 4, to: 5, phantom: true, hiddenFragment: true },
    { from: 5, to: 6 },
    { from: 6, to: 7, phantom: true, hiddenFragment: true },
    { from: 7, to: 8, phantom: true },
    { from: 8, to: 0 },
  ],
  miniPhantom: {
    position: [14, 3.2, 12],
    hiddenFragment: true,
  },
  fragments: [
    { position: [16, 4.2, -2], hidden: false },
    { position: [9, 5.7, -13], hidden: false },
    { position: [0, 7.6, -15], hidden: false },
    { position: [-16, 10.2, -3], hidden: false },
  ],
  tutorials: {
    movement: "Use WASD ou o joystick para atravessar as ilhas.",
    jump: "Pressione Espaço ou PULAR para alcançar a próxima plataforma.",
    attune: "As cordas vibram. SINTONIZE para revelar caminhos em outra frequência.",
    checkpoint: "Âncora estabilizada. Você retornará aqui se cair no vazio.",
    portal: "Reúna os sete Fragmentos de Frequência para despertar o portal.",
  },
  zorgLines: [
    "Observando… para fins estritamente científicos.",
    "Xul apostou que você cairia. Não caia.",
    "As cordas cantam quando você sintoniza. Ouça.",
    "Fragmentos rosa vivem em outra frequência.",
  ],
};

export default Object.freeze(level);
